name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, deploy
      run: |
        git remote add push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hughrawlinson/track-renderer"
        npm ci
        npm run deploy -o push
      env:
        CI: true
